baseurl: "https://brunamtq.github.io/project/"
languageCode: en-us
theme: hugo-theme-terminal
paginate: 5
params:
  centerTheme: no
  contentTypeName: posts
  fullWidthTheme: no
  showMenuItems: 2
  themeColor: "green"
languages:
  en:
    copyright: ''
    keywords: ''
    menu:
      main:
        - identifier: sobre
          name: Sobre
          url: /sobre
        - identifier: índice
          name: Índice
          url: /índice
    menuMore: Show more
    params:
      logo:
        logoHomeLink: /
        logoText: Terminal
    readMore: Read more
    readOtherPosts: Read other posts
    subtitle: A simple, retro theme for Hugo
    title: Bruna Barreto
publishDir: "docs/"

markup:
  goldmark:
    renderer:
      unsafe: true
